workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - firebase
        - app_store_connect
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.aya.isp
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Fetch iOS Firebase config
        script: |
          mkdir -p ios/Runner
          if [ -z "${GOOGLE_SERVICE_INFO_PLIST_B64:-}" ]; then
            echo "Missing GOOGLE_SERVICE_INFO_PLIST_B64 env var." >&2
            exit 1
          fi
          sanitized="$(printf "%s" "$GOOGLE_SERVICE_INFO_PLIST_B64" | tr -d '\r\n ')"
          printf "%s" "$sanitized" | base64 --decode > ios/Runner/GoogleService-Info.plist 2>/dev/null \
            || printf "%s" "$sanitized" | base64 -D > ios/Runner/GoogleService-Info.plist
          if [ ! -s ios/Runner/GoogleService-Info.plist ]; then
            echo "GoogleService-Info.plist decode failed or empty." >&2
            exit 1
          fi
      - name: Flutter pub get
        script: flutter pub get
      - name: Build iOS IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_ID
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
