workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Fetch iOS Firebase config
        script: |
          mkdir -p ios/Runner
          if [ -z "${GOOGLE_SERVICE_INFO_PLIST_B64:-}" ]; then
            echo "Missing GOOGLE_SERVICE_INFO_PLIST_B64 env var." >&2
            exit 1
          fi
          echo "$GOOGLE_SERVICE_INFO_PLIST_B64" | base64 --decode > ios/Runner/GoogleService-Info.plist 2>/dev/null \
            || echo "$GOOGLE_SERVICE_INFO_PLIST_B64" | base64 -D > ios/Runner/GoogleService-Info.plist
          if [ ! -s ios/Runner/GoogleService-Info.plist ]; then
            echo "GoogleService-Info.plist decode failed or empty." >&2
            exit 1
          fi
