workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Fetch iOS Firebase config
        script: |
          mkdir -p ios/Runner
          if [ -n "${GOOGLE_SERVICE_INFO_PLIST_B64:-}" ]; then
            echo "$GOOGLE_SERVICE_INFO_PLIST_B64" | base64 --decode > ios/Runner/GoogleService-Info.plist
          else
            cp "$CM_SECURE_FILES/GoogleService-Info.plist" ios/Runner/GoogleService-Info.plist
          fi
