workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Fetch iOS Firebase config
        script: |
          mkdir -p ios/Runner
          cp "$CM_SECURE_FILES/GoogleService-Info.plist" ios/Runner/GoogleService-Info.plist
